version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - save_cache:
          key: node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
          paths:
            - ~/.npm
      - run:
          name: Run Tests
          command: echo 0;
  publish: 
    docker: 
      - image: cimg/node:15.1
    steps: 
      - checkout
      - restore_cache:
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - node-deps-v1-{{ .Branch }}-{{checksum "package-lock.json"}}
      - run:
          name: install packages
          command: npm ci
      - run:
          name: build assets
          command: npm run build
      - run:
          name: build types
          command: npm run build-types
      - run:
          name: publish to npm
          command: |
            npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish
      - add_ssh_keys:
          fingerprints:
            - "3b:a9:1b:aa:03:ee:d1:47:8f:f7:1b:8b:e2:b5:1a:b5"
      - run:
          name: Install and configure dependencies
          command: |
            git config user.email "ci@enchuf.ar"
            git config user.name "cienchufar"
      - run:
          name: Build storybook pages
          command: npm run build-storybook
      
      - run:
          name: Deploy docs to gh-pages branch
          command: npx gh-pages --dist storybook-static
      

workflows:
  enchufar-components:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
      - publish:
          requires: 
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
